module Helloworld exposing (..)

{-| This file was mostly automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 2.3.1
  - `protoc` 3.19.4
  - the following specification file: `helloworld.proto`

-}

import Grpc
import Grpc.Internal exposing (Rpc(..))
import Protobuf.Decode
import Protobuf.Encode


{-| Calls the GRPC method 'SayHello' with the given `HelloRequest`.
-}
sayHello : Grpc.Rpc HelloRequest HelloReply
sayHello =
    Rpc
        { service = "Greeter"
        , package = "helloworld"
        , rpcName = "SayHello"
        , encoder = encodeHelloRequest
        , decoder = decodeHelloReply
        }


{-| Default for HelloReply. Should only be used for 'required' decoders as an initial value.
-}
defaultHelloReply : HelloReply
defaultHelloReply =
    { message = "" }


{-| Decode a `HelloReply` from Bytes
-}
decodeHelloReply : Protobuf.Decode.Decoder HelloReply
decodeHelloReply =
    Protobuf.Decode.message
        defaultHelloReply
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | message = a }) ]


{-| Encode a `HelloReply` to Bytes
-}
encodeHelloReply : HelloReply -> Protobuf.Encode.Encoder
encodeHelloReply value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.message ) ]


{-| `HelloReply` message
-}
type alias HelloReply =
    { message : String }


{-| Default for HelloRequest. Should only be used for 'required' decoders as an initial value.
-}
defaultHelloRequest : HelloRequest
defaultHelloRequest =
    { name = "" }


{-| Decode a `HelloRequest` from Bytes
-}
decodeHelloRequest : Protobuf.Decode.Decoder HelloRequest
decodeHelloRequest =
    Protobuf.Decode.message
        defaultHelloRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a }) ]


{-| Encode a `HelloRequest` to Bytes
-}
encodeHelloRequest : HelloRequest -> Protobuf.Encode.Encoder
encodeHelloRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.name ) ]


{-| `HelloRequest` message
-}
type alias HelloRequest =
    { name : String }
